### ISSUE TITLE
Prerelease channel for landlab

### ISSUE THREAD

**Issue by mcflugen** [conda-forge/landlab-feedstock#10]
I would like a prerelease channel for landlab like is described in conda-forge/gmt-feedstock#9. I tried created a `devel` branch and modified `conda-forge.yml` but that didn't quite do the trick. The package was still uploaded to the `main` channel, not `dev`.

@ocefpaf Do you have any ideas about what I did wrong?

**Comment by ocefpaf** [comment]
Please see this issue: https://github.com/conda-forge/conda-smithy/issues/897

I moved the package manually for now. See https://anaconda.org/conda-forge/landlab/files?version=1.9.0b3

**Comment by mcflugen** [comment]
All looks good. Thank you @ocefpaf!
