### ISSUE TITLE
conda installs an older build of landlab

### ISSUE THREAD

**Issue by mcflugen** [conda-forge/landlab-feedstock#46]
### Comment:

If I install *landlab* using *conda*, I get an older build of *landlab*,
```bash
$ conda create -n landlab landlab
$ conda activate landlab
$ conda list | grep landlab
# packages in environment at /Users/mcflugen/miniconda3/envs/landlab:
landlab                   2.5.0           py310h7f5fb2b_0    conda-forge
```
Instead of build 0, I would expect to get build 1. As @ocefpaf pointed out in conda-forge/admin-requests#432, *mamba* prioritizes build number and so installs the correct version, this is just an issue when *conda* is used. I'm not sure what *conda* prioritizes, perhaps fewer dependencies?

This is similar to the problem described in the above pull request but in this case the older build of *landlab* isn't "broken". The only difference between build 0 and build 1 is that build 1 includes *richdem* as a requirement but *landlab* can still function without *richdem*. *richdem* could perhaps be better described as an optional requirement. That is, people can use most of *landlab* without *richdem* but some functionality will not be available to them. The reason did this was for users who want to install *landlab* using *pip* as there aren't *richdem* builds for some platforms on *PyPI*.

@ocefpaf Do you have any thoughts on how to handle this?

**Comment by ocefpaf** [comment]
> I'm not sure what conda prioritizes, perhaps fewer dependencies?

Yep. Conda searches for the "easiest solve" while mamba searches for the most updated package. This is the only pain point (and difference) between the two alternatives.

> @ocefpaf Do you have any thoughts on how to handle this?

All we can do is to remove the broken one from the search space by moving it to the broken label.

**Comment by mcflugen** [comment]
Thank you, once again, @ocefpaf! I'll open up a pull request to label those builds as "broken".
